### ISSUE TITLE
secretKeyRef for `token` missing for Hetzner

### ISSUE THREAD

**Issue by itsezc** [kubermatic/machine-controller#1142]
While deploying the example yaml for Hetzner the following is thrown:

```secret/machine-controller-hetzner configured
Error from server: error when creating "hetzner-machinedeployment.yaml": admission webhook "machinedeployments.machine-controller.kubermatic.io" denied the request: validation failed: token is missing
```

Machine controller version: v1.40.1

**Comment by embik** [comment]
Hey, can you please try to clarify this issue? The Hetzner example does have a secretKeyRef, so I'm not sure I understand the issue title. https://github.com/kubermatic/machine-controller/blob/c3488bde1d9c840caaf57109719c68c701b13f05/examples/hetzner-machinedeployment.yaml#L40-L45

But the Secret needs to exist and have a token at the referenced key, can you please verify that's the case? If you could share the `MachineDeployment` YAML that you are actually trying to apply (since the example needs modification to work, I assume it's not 1:1 the file in the examples folder), that would help as well.

**Comment by itsezc** [comment]
The YAML I have for my deployment was based on the example:

```yaml
apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-hetzner
  namespace: kube-system
type: Opaque
stringData:
  token: ...
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: hetzner-machinedeployment
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerSpec:
        value:
          sshPublicKeys:
            - "..."
          cloudProvider: "hetzner"
          cloudProviderSpec:
            token:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-hetzner
                key: token
            serverType: "cx11"
            # Optional
            datacenter: ""
            location: "fsn1"
            image: "ubuntu-20.04"
            # Optional
            labels:
              my: label
          operatingSystem: "ubuntu"
          operatingSystemSpec:
            distUpgradeOnBoot: false
      versions:
        kubelet: 1.23.1
```
