### ISSUE TITLE
KubeVirt VM with rhel: kubelet is not started

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/machine-controller#1247]
- Create a KubeVirt with rhel using the following MD:
```
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: ln-kubevirt-machine-2
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      name: foo
      machine: ln-kubevirt-machine-2
  template:
    metadata:
      labels:
        name: foo
        machine: ln-kubevirt-machine-2
    spec:
      providerSpec:
        value:
          sshPublicKeys:
            - "redacted"
          cloudProvider: "kubevirt"
          cloudProviderSpec:
            auth:
              kubeconfig:
                value: 'redacted'
            virtualMachine:
              dnsConfig:
                nameservers: 
                - "8.8.8.8"
              dnsPolicy: ""
              template:
                cpus: "1"
                memory: "4096M"
                primaryDisk:
                  osImage: http://10.244.2.19/rhel.img
                  size: "20Gi"
                  storageClassName: longhorn
            # affinity:
            #   podAffinityPreset: "" # Allowed values: "", "soft", "hard"
            #   podAntiAffinityPreset: "" # Allowed values: "", "soft", "hard"
            #   nodeAffinityPreset: 
            #     type: "" # Allowed values: "", "soft", "hard"
            #     key: "foo"
            #     values:
            #     - bar
          # Can also be `centos`, must align with he configured registryImage above
          operatingSystem: "rhel"
          operatingSystemSpec:
            distUpgradeOnBoot: false
            disableAutoUpdate: true
      versions:
        kubelet: 1.22.5
```

- The VM starts, but no `Node` joins the cluster.
- OS : rhel 8.4

The reason is the following `yum install` that fails:
```yum-plugin-versionlock```

-> No docker, neither kubelet is started.
