### ISSUE TITLE
Machine deployment fails in air-gapped environment when using containerd runtime

### ISSUE THREAD

**Issue by holgers66** [kubermatic/machine-controller#1320]
when using the containerd runtime the machine controller runs the following command when deploying new machines:

yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

That is line 120 here: https://github.com/kubermatic/machine-controller/blob/release/v1.43/pkg/containerruntime/containerd.go

In a completely air-gapped installation this fails, causing the setup.service on the worker machines to fail, so the machine deployment hangs with "machine has no node ref" errors.

**Comment by holgers66** [comment]
This is a very urgent issue. It's blocking SVA for their air-gapped showcase at KV Brandenburg.

**Comment by hc2p** [comment]
We don't have that problem in the offline-reference setup. Have you configured containerd mirrors in the same way? 

```
containerRuntime:
  containerd:
    registries:
      "*":
        mirrors:
        - nexus-url
      docker.io:
        mirrors:
        - nexus-url
```
https://github.com/kubermatic/offline-reference-setup/blob/main/infra/aws/kkp-cluster/kubeone.yaml#L24-L29
