### ISSUE TITLE
Hetzner server loses its IPv4 after 7 days

### ISSUE THREAD

**Issue by renchap** [kubermatic/machine-controller#1587]
I am using Kubeone 1.26.0 to deploy a K8s cluster in Hetzner. The worker nodes are all managed by `machine-controller`.

Nodes are running Ubuntu 22.04

The nodes are loosing their public IPv4 network configuration 7 days after booting.

I am having issues troubleshooting the exact source of the issue, but here are my findings:
- The servers are part of a VPC with a private address. This address is still configured after 7 days
- After booting, the public IP address for the node is correctly show in `ifconfig eth0`
- After 7 days, `ifconfig eth0` no longer shows an IPv4. This is most probably because a DHCP lease expired?
- `/etc/netplan` is empty. `50-cloud-init.cfg` was deleted by `/opt/bin/bootstrap`
- the cluster is using Cilium (is it related?)

This caused production issues for us, so I rolled back our nodes to Ubuntu 22.04, and remove Cilium to see if it was causing the issue. But I think I can redeploy a new node pool for testing purposes if needed.

Here is an example `MachineDeployment` showing this behaviour:

```yaml
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  name: m-s-m-1
  namespace: kube-system
spec:
  minReadySeconds: 60
  paused: false
  progressDeadlineSeconds: 600
  replicas: 16
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      workerset: m-s-m-pool1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workerset: m-s-m-pool1
      namespace: kube-system
    spec:
      metadata:
        creationTimestamp: null
        labels:
          workerset: m-s-m-pool1
          property: m.s
      providerSpec:
        value:
          caPublicKey: ""
          cloudProvider: hetzner
          cloudProviderSpec:
            image: ubuntu-22.04
            labels:
              main-workers: m-s-m-pool1
            location: fsn1
            networks:
              - "xxx"
            firewalls:
              - "k8s-1-fw"
            serverType: ccx32
          operatingSystem: ubuntu
          operatingSystemSpec:
            distUpgradeOnBoot: true
          sshPublicKeys:
            - |
              xxx
      versions:
        kubelet: 1.25.7
```

**Comment by dcardellino** [comment]
I have a similar issue. But I have this issue in a daily basis. Someone told me this could be an issue with unattended upgrades .. It is no issue with 22.04 we are running 20.04 and have the same problems.

**Comment by renchap** [comment]
I can confirm we just had the same problem with Ubuntu 20.04, trying to rollback to 18.04.

Could this be related to https://github.com/kubermatic/operating-system-manager/pull/273 ?

**Comment by 7oku** [comment]
Just giving context here: In our case the daily apt  auto upgrade updated systemd on all worker nodes. After that, all machines lost their DNS servers (and couldn't fetch them again from Hetzner DHCP). The only solution was to reboot the node, however, that resulted in the node being in the provisioning loop which is to be fixed by #273.

**Comment by maltechx** [comment]
My Nodes are loosing their DNS config and IPv4 within 24 hours. I have to replace all nodes daily, because if one goes down all other can't pull images anymore. 
Has anyone found a fix to prevent that?

**Comment by kron4eg** [comment]
Recently, in completely different environment we hit the issue on ubuntu 22.04 + cilium + unnatended-upgrade. unnatended-upgrade runs at around 6:30 UTC, upgrades the systemd and this restarts the network, which in turn causes network to die until the reboot (I suspect some kind of dead lock in cilium).

If you replace the node, whole thing repeats next morning.

**Comment by kron4eg** [comment]
I've was able to workaround this with running `apt upgrade; reboot` inside the `tmux`. tmux was needed to ensure the reboot will run even after the network comes down.

**Comment by kron4eg** [comment]
In the tests, if we replaced cilium with canal, everything was OK.

**Comment by kron4eg** [comment]
P.S.
On a side note, since kubeone v1.6 it got support for helm releases, now I often use such kubeone config.

```
...
clusterNetwork:
  cni:
    external: {}

helmReleases:
  - chart: https://github.com/flannel-io/flannel/releases/download/v0.21.3/flannel.tgz
    releaseName: flannel
    namespace: kube-system
```
