### ISSUE TITLE
Support running shell script on Node boot

### ISSUE THREAD

**Issue by renchap** [kubermatic/machine-controller#1729]
In some environments, you might need to run some shell commands on node boot.

For example, with Hetzner, you need to enable [Receive Packet Steering](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Performance_Tuning_Guide/network-rps.html) on your Cloud servers if you are managing a lot of packets on some pods, otherwise you will have the IRQs for the network card on one core, saturating it and slowing everything down.

I could not find a way to have a `MachineDeployment` run a command after booting on a node.

I tried various forms around this, but the resulting `OperatingSystemConfig` never include those:

```yaml
      providerSpec:
        value:
          cloudProvider: hetzner
          cloudProviderSpec:
            image: ubuntu-22.04
          operatingSystem: ubuntu
          operatingSystemSpec:
            distUpgradeOnBoot: true
            provisioningConfig:
              modules:
                runcmd:
                - "echo \"test\" > /tmp/test_bootstrap"
```

This object is accepted and written on the k8s server, but the `runcmd` script is never written anywhere I can see. I am not sure if this is a bug, or a missing feature.

I understood that an alternative would be to have a custom `OperatingSystemProfile`, but it means keeping it up-to-date with newer versions, which is burdensome.
