### ISSUE TITLE
KubeVirt GenerateRandMAC

### ISSUE THREAD

**Issue by chifu1234** [kubermatic/machine-controller#1752]
## Bug Report

**Describe the bug**

When setting macAddress on the bridge of the VM, not every CNI implementation supports a deterministic MAC as they assign a MAC themself. The VM then gets the wrong MAC, and thus, no traffic is switched to the VM.

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testerli-6cbbdfbcf7-bfrgv
  namespace: cluster-rb489cv8zn
spec:
  dataVolumeTemplates:
      labels:
    spec:
      domain:
        devices:
          interfaces:
          - bridge: {}
            macAddress: c2:4b:c4:9c:a5:f3
            name: default
...
```

**Expected behavior**

When creating Machine Deployment I can configure that kubermatic will not configure a RandomMac and the VM Object.
