### ISSUE TITLE
Implement static IP management

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#262]
Implement static IP management.

The Machine object will be extended to include a dedicated `Network` object inside the `ProviderConfig`:
```yaml
apiVersion: "machine.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: machine1
spec:
  metadata:
    name: node1
  providerConfig:
    network:
      cidr: "192.168.1.129/25"
      gateway: "192.168.1.1"
      # Explicitly making it a dedicated object to enable extending the dns settings
      dns:
        servers:
        - "192.168.1.1"
``` 

The machine-controller will use this information when generating the cloud-init/ignition data to configure the network of the instance.
`machine.Spec.ProviderConfig.Network` will be a pointer to express the network configuration is optional. Following the kubernetes documentation on `Optional vs. Required` https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required

- [ ] Add support for network configuration in machine object
- Configuration implemented for every OS
  - [x] CoreOS
  - [ ] CentOS
  - [ ] Ubuntu
- Tests
  - [ ] Each operating has a test-case (fixture/golden file is fine)
  - [ ] E2E test covering vSphere
