### ISSUE TITLE
Enable population of ssh_authorized keys through metadata service e.g. Packet

### ISSUE THREAD

**Issue by gaberger** [kubermatic/machine-controller#556]
Packet's control plane is authoritative for project data and maintains a list of authorized ssh_keys on a project/organization level. I would like for the userdata template to pull ssh_authorized_keys from the metadata service `https://metadata.packet.net/2009-04-04/meta-data/public-keys` and merge with ProviderSpec. 

Note: currently, not populating that key will produce a cloud-init error: 
```2019-05-31 21:04:04,746 - util.py[DEBUG]: Applying ssh credentials failed!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py", line 189, in handle
    keys.extend(cfgkeys)
TypeError: 'NoneType' object is not iterable
```
cc: @deitch

**Comment by alvaroaleman** [comment]
What about using a Daemonset that does this instead?

The machineSpec is immutable after a machine was created because the controller intentionally can not do in-place upgrades, instead changes to a `machineSpec` have to be done by modifying a MachineDeployment in order to make sure the integrity of the fleet as a whole is being kept.

**Comment by deitch** [comment]
I think that there are two issues here:

1. cloudconfig falls down when the `ssh_authorized_keys` entry is blank. It probably should prevent a blank entry, but also should handle the blank entry gracefully
2. Can we find a way to include the cloud provider's ssh keys - however they are defined (in this case, Packet's, they are project level) - in the install?

**Comment by deitch** [comment]
> Can you list the steps you undertook to end up with that error?

When @gaberger showed it to me, it was because cloud-config looked as follows:

```yml
#cloud-config

hostname: cluster-test-1-deployment-5577f9c56d-z8fvj
# Never set the hostname on AWS nodes. Kubernetes(kube-proxy) requires the hostname to be the private dns name


ssh_pwauth: no

ssh_authorized_keys:

write_files:
- path: "/etc/systemd/journald.conf.d/max_disk_use.conf"
  content: |
    [Journal]
    SystemMaxUse=5G

# etc. etc.
```

See the empty `ssh_authorized_keys`
