### ISSUE TITLE
Autoscaling

### ISSUE THREAD

**Issue by luisdavim** [kubermatic/machine-controller#605]
Hi, is it possible to integrate the cluster autoscaler with the machine-controller? Or does the controller provide the autoscaling features?

**Comment by alvaroaleman** [comment]
Hey, thanks for inquiring. What we need is a cluster-autoscaler implementation that supports clusterapi v1alpha1 as backend. @frobware has built one already, althought it isn't merged: https://github.com/kubernetes/autoscaler/pull/1866

Other than that, we'd need to fix https://github.com/kubermatic/machine-controller/issues/564 (althought that doesn't matter if you run on a platform that does have a cloudprovider)

**Comment by luisdavim** [comment]
thanks @alvaroaleman

**Comment by kron4eg** [comment]
So, upstream clusterAPI change got merged and released. And machine-controller doesn't need to do anything!

In order to make autoscaling work, MachineDeployments or MachineSets should be annotated like this:

```yaml
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    cluster.k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
    cluster.k8s.io/cluster-api-autoscaler-node-group-max-size: "10"
```

But such annotations are out of machine-controller scope and should be provided by the user.
See more info at https://github.com/kubernetes/autoscaler/pull/1866
