### ISSUE TITLE
vSphere: Support VM templates

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/machine-controller#670]
When creating a MachineDeployment for vSphere specifying VM template instead of a VM e.g.

```
          cloudProvider: vsphere
          cloudProviderSpec:
            allowInsecure: false
            cluster: cl-1
            cpus: 1
            datacenter: dc-1
            datastore: ds-1
            folder: /dc-1/vm/
            memoryMB: 2000
            password: ""
            templateVMName: /dc-1/vm/Ubuntu1804Template # Name of a VM template
            username: ""
            vmNetName: ""
            vsphereURL: ""
          operatingSystem: ubuntu
```

 the following error occurs:

`E0128 21:38:57.878868       1 machine.go:361] Failed to reconcile machine "ubuntu-test-64957bbf86-sncrf": An error of type = InvalidConfiguration, with message = failed to create cloned vm: 'error when waiting for result of clone task: A specified parameter was not correct: spec.location.pool' occurred`

The problem is that when cloning a VM template the resource pool needs to be specified, while when cloning a VM it defaults to the storage pool of the VM itself.

https://code.vmware.com/apis/358/vsphere/doc/vim.vm.RelocateSpec.html
