### ISSUE TITLE
Assign types to all machine addresses

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/machine-controller#709]
The `.Status.Addresses` struct (`[]corev1.Address`) for the Machine object contains the address of the machine and the type of the address. The type is used to make a difference between internal and external IP addresses, as well as, between IP addresses and hostnames.

Currently, we don't set the address type, for example:
```
addresses:
  - address: 35.180.54.64
    type: ""
  - address: ec2-35-180-54-64.eu-west-3.compute.amazonaws.com
    type: ""
  - address: 172.31.92.180
    type: ""
  - address: ip-172-31-92-180.eu-west-3.compute.internal
    type: ""
```

This makes impossible to know is an address a hostname or an address and is the address private or external.

This can be useful for operators and some other use-cases, such as the NodeCSRApprover controller.

**Acceptance criteria**
* `machine-controller` automatically assigns the address type to all addresses
