### ISSUE TITLE
vSphere: Support secrets for cloud provider config

### ISSUE THREAD

**Issue by maxilampert** [kubermatic/machine-controller#742]
Installation of a Kubernetes cluster with kubeone creates a secret for the cloud-config on master nodes

``[Global]``
``secret-name = "cloud-provider-credentials"``
``secret-namespace = "kube-system"``

while the machine-controller puts in user and password in plain into the config of the worker

``[Global]``
``user              = "administrator@vsphere.local"``
``password          = "test123"``

support for secret config usage should be added to normalize configuration between master & worker nodes and reduce security attack surface by not having the password in plain on the hosts.

**Comment by toschneck** [comment]
@maxilampert If you currently manage your maschine deployment object separately, you already can do it:
```yaml
    spec:
      providerSpec:
        value:
          cloudProvider: vsphere
          cloudProviderSpec:
            allowInsecure: true
            cluster: cl-1
            cpus: 2
            datacenter: dc-1
            datastore: exsi-nas
            datastoreCluster: ''
            diskSizeGB: 10
            folder: /dc-1/vm/kubermatic/tobi-k1
            memoryMB: 4096
            password: ''
            resourcePool: ''
            templateVMName: kubeone-ubuntu-18.04
            username: ''
            vmNetName: ''
            vsphereURL: ''
          operatingSystem: ubuntu
          operatingSystemSpec:
            distUpgradeOnBoot: false
          overwriteCloudConfig: |+
            [Global]
            secret-name = "cloud-provider-credentials"
            secret-namespace = "kube-system"
            port = "443"
            insecure-flag = "0"

            [VirtualCenter "1.1.1.1"]

            [Workspace]
            server = "1.1.1.1"
            datacenter = "dc-1"
            default-datastore="exsi-nas"
            resourcepool-path="tobi-k1"
            folder = "TODO"

            [Disk]
            scsicontrollertype = pvscsi

            [Network]
            public-network = "Loodse Default"
```
