### ISSUE TITLE
Slow metrics with OpenStack and secretKeyRef

### ISSUE THREAD

**Issue by balous** [kubermatic/machine-controller#894]
I experience a situation where Prometheus is unable to scrape machine-controller metrics. When I try it with curl, I get:

```
$ curl localhost:8085/metrics
curl: (52) Empty reply from server
```

I figured out that the 10 second http write timeout just expires.

The cluster contains 8 machines running in OpenStack. Their `cloudProviderSpec` credentials are configured with `secretKeyRef`:

```
    providerSpec:
      value:
        cloudProvider: openstack
        cloudProviderSpec:
          domainName:
            secretKeyRef:
              key: domain-id
              name: cloud-config
              namespace: kube-system
          flavor: t3.20c89r650d
          identityEndpoint:
            secretKeyRef:
              key: auth-url
              name: cloud-config
              namespace: kube-system
          image: ubuntu-18.04-amd64

...
```
A single machine instance contains 5 secret references.

When serving the metrics, machine-controller performs kubernetes API query for each secret reference. This is repeated for every metric, for every machine. Tens of queries are performed in such a small setup and the 10 second timeout is reached easily.

So I've tried to convert `cloudProviderSpec` to direct values. In a cluster with three machines the `scrape_duration_seconds` metrics dropped from about a second to 0.01s.

Looking into the code and into other cloud's examples, I've got impression that the situation should be similar for other cloud providers too.
