### ISSUE TITLE
machine upscale fails after password change

### ISSUE THREAD

**Issue by uvwild** [kubermatic/machine-controller#939]
I tried to scale up my k8s base cluster using the machine controller after a forced provider password change.

`ks scale machinedeployments democluster-pool1 --replicas=9`

however, the machine-controller fails with:

`E0330 xxxxmachineset_controller.go:141] Failed to reconcile MachineSet "kube-system/democluster-pool1-67648bd9b4": failed to sync Machineset replicas: admission webhook "machine-controller.kubermatic.io-machines" denied the request: failed to default machineSpec: An error of type = InvalidConfiguration, with message = A request has been rejected due to invalid credentials which were taken from the MachineSpec: Authentication failed occurred; admission webhook "machine-controller.kubermatic.io-machines" denied the request: failed to default machineSpec:
`
    the mc pod references the cloud-provider-credentials which I checked.
    I also updated the cloud-config on the existing nodes with the new pw to be sure

but still authentication error. what can i do?
where are those machinespecs hidden?

thanks

**Comment by kron4eg** [comment]
The issue is that you've changed the password and machine-controller-webhook can not validate your machineDeployment any longer (it makes API calls).
Please rerun `kubeone apply` (or kubeone install) will all the flags you usually do, with correct password set in the environment or credentials-file. That will reinstall your credentials back to the cluster. The secret object where those are stored named `cloud-provider-credentials` in `kube-system` namespace.

**Comment by uvwild** [comment]
thanks for the feedback.
However, the kubeone apply run (multiple times without errors)  fixes the invalid configuration error.
but another issue with webhook remains.

`Error updating Endpoint Slices for Service kube-system/machine-controller-webhook: Error updating machine-controller-webhook-5tjj2 EndpointSlice for Service kube-system/machine-controller-webhook: Operation cannot be fulfilled on endpointslices.discovery.k8s.io "machine-controller-webhook-5tjj2": the object has been modified; please apply your changes to the latest version and try again
`
Which objects should I force delete to recover this versioning issue? i can see the update tag in the endpointslice object.
but I am not sure which versions of which objects are compared to make this fail.

there seem to be a general issues with this endpointsslices as well  https://github.com/kubernetes/kubernetes/issues/92928

kubeone 1.2.0
k8s 1.18.6 using openstack provider
docker.io/kubermatic/machine-controller:v1.25.0

**Comment by uvwild** [comment]
i deleted the endpointslices and the machine-controller-webhook and ran kubeone apply again....
This solved the endpointslice issue.
Now the reconcile error is:

`E0406 14:12:42.684586 1 machine_controller.go:363] Failed to reconcile machine "democluster-pool1-67648bd9b4-xtft9": failed to create machine at cloudprovider, due to instance 5352e4b7-0d84-4938-92e6-0d5f686ce899 became not active: instance became not active after 10.000000 seconds`

I think the timeout is too low for openstack OTC. Where can I change this?
the machinespec defines a progressDeadlineSeconds to 10 minutes? the log talks about 10 seconds?!?!

```
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 9

```

**Comment by kron4eg** [comment]
@uvwild openstack specific config have you covered. With help of instanceReadyCheckPeriod and instanceReadyCheckTimeout.

See example: https://github.com/kubermatic/machine-controller/blob/master/examples/openstack-machinedeployment.yaml#L16-L17

**Comment by uvwild** [comment]
thanks, that looks good. 
However, I am confused since this secret does **not** exist on my cluster and instead the credentials are in cloud-provider-credentials ?!? is that a version issue? i use docker.io/kubermatic/machine-controller:v1.25.0

**Comment by kron4eg** [comment]
>Rerunning the cluster provisioning would remove my change?!?

If you would supply `--upgrade-machine-deployments` that will only upgrade machineDeployment (i.e. change kubelet version). No other changes will be performed on existing machineDeployment objects.

**Comment by uvwild** [comment]
ok a more specific kubeone run is helpful.
But our installer does not use this machine-controller config. 
Instead it creates  secret/cloud-provider-credentials for openstack credentials when running kubeone. 
The section for the machinedeployments is based on cloudProviderSpec. I tried adding the 2 values instanceReadyXXX  to the cloudProviderSpec  but this doesnt change anything for the machine creation timeout.  
```
      providerSpec:
        value:
          cloudProvider: openstack
          cloudProviderSpec:
            availabilityZone: eu-de-01
            flavor: s2.large.4
            image: Standard_Ubuntu_20.04_prev
            instanceReadyCheckPeriod: 120
            instanceReadyCheckTimeout: 300
            network: a91554ed-f2a8-46bc-ad26-fd8363775f4a
            rootDiskSizeGB: 50
            securityGroups:
            - secgroup_k8sworker
            subnet: garden_subnet
            tags:
              democluster-workers: pool1
          operatingSystem: ubuntu
          operatingSystemSpec:
            distUpgradeOnBoot: false
          sshPublicKeys:
          - |
            ssh-rsa   xxxxxxxx-the-key
      versions:
        kubelet: 1.18.6      
```

I dont see the relation to the secret/machine-controller-openstack in the example.  Is it a version issue? i see the code is at v1.27.4
Also I cannot see which code is referencing those values. Dont I require a specific reference to use that value in the machinecontroller? or is that an implcit one using templated object naming?
